import secrets
from typing import Annotated, Protocol

from ..types import (
    ErrorResponse,
    ZaloAPIError,
    BotInfo,  
    WebhookInfo,
    MessageInfo,
    Event
)
from ..config import ZaloAPIConfig
from .http import fetch
from .context import Context

class UnconfiguredWebhook: 
    """Represents the state of the bot where webhook have not yet configured"""
class ConfiguredWebhook:
    """Represents the state of the bot where webhook is configured"""
type BotStates = Annotated[
    UnconfiguredWebhook | ConfiguredWebhook,
    "Represents the states of the bot"
]

class AsyncWebhookHandler(Protocol):
    async def __call__(self, ctx: Context) -> None: ...

class ZaloBot[S: BotStates = UnconfiguredWebhook]:
    def __init__(
        self,
        BOT_TOKEN: str,
        *,
        _secret_token: str | None = None
    ):
        self._BOT_TOKEN: str = BOT_TOKEN
        self._base_url: str = f"{ZaloAPIConfig.BASE_URL}/bot{BOT_TOKEN}"
        self._webhook_handlers: list[AsyncWebhookHandler] = [] 
        if _secret_token is not None:
            self._secret_token: str = _secret_token

    async def getMe(self) -> BotInfo:
        url = f"{self._base_url}/getMe" 
        
        res = await fetch(url, result_schema=BotInfo)

        if isinstance(res, ErrorResponse):
            raise ZaloAPIError(
                res.error_code,
                res.description
            ) 
        
        return res.result
                      
    async def getUpdates(self, timeout: int = 30) -> Event:
        url = f"{self._base_url}/getUpdates"
        
        payload = {
            "timeout": timeout
        }

        res = await fetch(url, result_schema=Event, method="POST", body=payload, timeout=timeout)

        if isinstance(res, ErrorResponse):
            raise ZaloAPIError(
                res.error_code,
                res.description
            )

        return res.result

    async def setWebhook(
        self: ZaloBot[UnconfiguredWebhook],
        webhook_url: str,
        secret_token: str,
    ) -> WebhookInfo:
        url = f"{self._base_url}/setWebhook"
        
        payload = {
            "url": webhook_url,
            "secret_token": secret_token
        }

        res = await fetch(url, result_schema=WebhookInfo, method="POST", body=payload)

        if isinstance(res, ErrorResponse):
            raise ZaloAPIError(
                res.error_code,
                res.description
            )

        return res.result
    
    async def deleteWebhook(self) -> WebhookInfo:
        url = f"{self._base_url}/deleteWebhook"
        
        res = await fetch(url, result_schema=WebhookInfo)

        if isinstance(res, ErrorResponse):
            raise ZaloAPIError(
                res.error_code,
                res.description
            )

        return res.result

    async def getWebhookInfo(self) -> WebhookInfo:
        url = f"{self._base_url}/getWebhookInfo"
        
        res = await fetch(url, result_schema=WebhookInfo)

        if isinstance(res, ErrorResponse):
            raise ZaloAPIError(
                res.error_code,
                res.description
            )

        return res.result
    
    async def sendMessage(self, chat_id: str, text: str) -> MessageInfo:
        url = f"{self._base_url}/sendMessage"
        
        payload = {
            "chat_id": chat_id,
            "text": text
        }
        res = await fetch(url, result_schema=MessageInfo, method="POST", body=payload)

        if isinstance(res, ErrorResponse):
            raise ZaloAPIError(
                res.error_code,
                res.description
            )

        return res.result


    async def sendPhoto(self, chat_id: str, caption: str, photo_url: str) -> None:
        raise NotImplementedError()

    async def sendSticker(self, chat_id: str, sticker: str) -> None:
        raise NotImplementedError()

    async def sendChatAction(self, chat_id: str, action: str) -> None:
        raise NotImplementedError()

    async def configure_webhook(
        self: ZaloBot[UnconfiguredWebhook],
        url: str
    ) -> ZaloBot[ConfiguredWebhook]:
        """Upgrades the bot to support webhook mechanisms.

        Warning: 
            This method will raise a `ZaloAPIError` if you attempt to configure 
            a webhook when one already exists.
        """
        secret_token = secrets.token_urlsafe(192)
        _ = await self.setWebhook(url, secret_token)
        
        return ZaloBot(self._BOT_TOKEN, _secret_token = secret_token)
    
    def get_secret_token(self: ZaloBot[ConfiguredWebhook]):
        """Gets the secret token generated by the configure_webhook"""
        return self._secret_token

    def add_webhook_handler(
        self: ZaloBot[ConfiguredWebhook],
        handler: AsyncWebhookHandler
    ) -> None:
        """Registers a handler to handle on webhook event update"""
        self._webhook_handlers.append(handler)

    async def dispatch_webhook_handlers(
        self: ZaloBot[ConfiguredWebhook],
        update_event: Event
    ) -> None:
        """Run all handlers given a webhook event"""
        for handler in self._webhook_handlers:
            await handler(Context(_update=update_event, _bot=self))
