from typing import Protocol
from ..types import MessageInfo

class ZaloBotAPI(Protocol):
    async def sendMessage(self, chat_id: str, text: str) -> MessageInfo: ...
    async def sendPhoto(self, chat_id: str, caption: str, photo_url: str) -> None: ...
    async def sendSticker(self, chat_id: str, sticker: str) -> None: ...
    async def sendChatAction(self, chat_id: str, action: str) -> None: ...
